include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = RevealLoader2

RevealLoader2_FILES = MKRLRootListController.m
RevealLoader2_FRAMEWORKS = UIKit
RevealLoader2_PRIVATE_FRAMEWORKS = Preferences
RevealLoader2_EXTRA_FRAMEWORKS = AltList
RevealLoader2_INSTALL_PATH = /Library/PreferenceBundles
RevealLoader2_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk